# Generated by Django 5.1.2 on 2024-11-01 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LikesAnchor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anchor_type', models.SmallIntegerField(choices=[(1, 'POST'), (2, 'COMMENT')])),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent_likes_anchor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='likes_app.likesanchor')),
            ],
            options={
                'unique_together': {('parent_likes_anchor', 'user')},
            },
        ),
    ]
