# Generated by Django 5.1.2 on 2024-10-20 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts_app', '0006_remove_post_image_alter_postimage_image_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('posts', models.ManyToManyField(related_name='tags', to='posts_app.post')),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='post_tags_a_name_2b0190_idx'), models.Index(fields=['count'], name='post_tags_a_count_f25322_idx')],
            },
        ),
    ]
