# Generated by Django 5.1.2 on 2024-11-01 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentsAnchor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anchor_type', models.SmallIntegerField(choices=[(1, 'POST')])),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent_comments_anchor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='comments_app.commentsanchor')),
            ],
            options={
                'indexes': [models.Index(fields=['parent_comments_anchor', 'created_at'], name='comments_ap_parent__04bd95_idx')],
            },
        ),
    ]
