# Generated by Django 5.1.2 on 2024-10-19 18:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_label', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('url', models.CharField(max_length=256)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='')),
                ('priority', models.FloatField(default=0, help_text='Lower numbers are shown first', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='links', to='menu_app.menu')),
            ],
        ),
    ]
