# Generated by Django 5.1.2 on 2024-10-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_label',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
