# Generated by Django 5.1.2 on 2024-10-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0002_post_username_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
