# Generated by Django 5.1.2 on 2024-10-18 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0005_move_post_image_to_separate_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image_data',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
