# Generated by Django 5.1.2 on 2024-10-29 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0001_initial'),
        ('posts_app', '0007_remove_post_username_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='image_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_app.media'),
        ),
    ]
